import type { Metadata } from "next";
import { DM_Serif_Text, DM_Sans } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-DMSans",
  display: "swap",
});

const DMSerifText = DM_Serif_Text({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-DMSerifText",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${DMSans.className}`}>{children}</body>
    </html>
  );
}
